### ISSUE TITLE
arruma logo isso pelo amor de deeeeeeusssss

### ISSUE THREAD

**Issue by bitchex** [weizinai/StardewValleyMods#10]
﻿[20:05:27 ERROR Help Wanted Redux For 1.6] Failed to apply 'weizinai.StardewValleyMod.HelpWanted.Patcher.SlayMonsterQuestPatcher' patcher. Technical details:
System.ArgumentException: No such field defined in class StardewValley.Quests.SlayMonsterQuest, Stardew Valley, Version=1.6.15.24354, Culture=neutral, PublicKeyToken=null (Parameter 'random')
   at HarmonyLib.MethodPatcher.EmitCallParameter(MethodInfo patch, Dictionary`2 variables, LocalBuilder runOriginalVariable, Boolean allowFirsParamPassthrough, LocalBuilder& tmpObjectVar, List`1 tmpBoxVars)
   at HarmonyLib.MethodPatcher.<>c__DisplayClass36_0.<AddPrefixes>b__0(MethodInfo fix)
   at HarmonyLib.MethodPatcher.AddPrefixes(Dictionary`2 variables, LocalBuilder runOriginalVariable)
   at HarmonyLib.MethodPatcher.CreateReplacement(Dictionary`2& finalInstructions)
   at HarmonyLib.PatchFunctions.UpdateWrapper(MethodBase original, PatchInfo patchInfo)
   at HarmonyLib.PatchProcessor.Patch()
   at weizinai.StardewValleyMod.HelpWanted.Patcher.SlayMonsterQuestPatcher.Apply(Harmony harmony) in C:\Projects\StardewValleyMods\HelpWanted\Patcher\SlayMonsterQuestPatcher.cs:line 23
   at weizinai.StardewValleyMod.Common.Patcher.HarmonyPatcher.Apply(Mod mod, IPatcher[] patchers) in C:\Projects\StardewValleyMods\Common.Patcher\HarmonyPatcher.cs:line 20

**Comment by weizinai** [comment]
I have fixed it in version 1.3.0.
